# {xrst_begin .readthedocs.yaml}
# {xrst_comment_ch #}
#
# Example Read the Docs Configuration
# ###################################
#
# This Example File
# *****************
# {xrst_literal}
#
# {xrst_end .readthedocs.yaml}
version: 2

build:
   os: "ubuntu-20.04"
   tools:
      python: "3.10"
   commands:
      #
      # xrst
      - pip install xrst
      #
      # build/html
      # The xsrst html_directory for this configuration is build/html
      - xrst --page_source --html_theme furo
      #
      # _readthedocs/html
      # The directory that Read the Docs uploads when commands is used
      - mkdir _readthedocs
      - cp -r build/html _readthedocs/html
