# SPDX-License-Identifier: GPL-3.0-or-later
# SPDX-FileCopyrightText: 2020-22 Bradley M. Bell <bradbell@seanet.com>
#
# BEGIN_PROJECT_NAME
[project_name]
data = 'xrst'
# END_PROJECT_NAME
#
# BEGIN_DIRECTORY
# This is same as the default and only used as an example
[directory]
project_directory = '.'
rst_directory     = 'rst'
# END_DIRECTORY
#
# BEGIN_ROOT_FILE
[root_file]
default = 'example/example.xrst'
user    = 'user/user.xrst'
dev     = 'xrst/__init__.py'
# END_ROOT_FILE
#
# BEGIN_HTML_THEME_OPTIONS
# This is same as the default and only used as an example
[html_theme_options.sphinx_book_theme]
show_toc_level = 4

[html_theme_options.sphinx_rtd_theme]
navigation_depth = -1
titles_only      = true
# END_HTML_THEME_OPTIONS
#
# BEGIN_PREAMBLE
[preamble]
rst_substitution = '''
.. |space| unicode:: 0xA0
.. |tab| replace:: |space| |space| |space|
'''
latex_macro = [
   '\newcommand{\B}[1]{ {\bf #1} }' ,
   '\newcommand{\R}[1]{ {\rm #1} }' ,
]
# END_PREAMBLE
# -----------------------------------------------------------------------------
# BEGIN_PROJECT_DICTIONARY
[project_dictionary]
data = [
   # file extensions
   '''
      cpp
      py
      rst
   ''',
   # python types
   '''
      str
   ''',
   # special words
   '''
      factorial
   ''',
]
# END_PROJECT_DICTIONARY
# -----------------------------------------------------------------------------
# BEGIN_NOT_IN_INDEX
[not_in_index]
data = [
  # articles and prepositions
  '''
      a
      and
      by
      for
      of
      the
      this
      to
  ''',
  # words that are use in many different pages of the documentation
  '''
    command
    example
    file
    purpose
    syntax
  ''',
  # python regular expression for month-day used in release notes
  '[0-9]{2}-[0-9]{2}',
  # python regular expression for year.month.day used in version number
  '[0-9]{4}[.][0-9]{1,2}[.][0-9]{1,2}',
]
# END_NOT_IN_INDEX
