# SPDX-License-Identifier: GPL-3.0-or-later
# SPDX-FileCopyrightText: Bradley M. Bell <bradbell@seanet.com>
# SPDX-FileContributor: 2024 Bradley M. Bell
# ----------------------------------------------------------------------------
# Use the following to verify yml syntax before commiting:
# https://yamlchecker.com/
#
# The name for this workflow
name: bash-workflow
#
# A short description of this workflow
run-name: Test using bash on windows, ubuntu and macos.
#
# This worflow will be run on any push to the repository
on:
  push:
    branches:
      master
#
jobs:
  #
  check_all:
    #
    strategy:
      matrix:
        os: [ windows-latest, ubuntu-latest , macos-latest ]
    #
    runs-on: ${{ matrix.os }}
    steps:
      #
      # actions
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.12'
      #
      - name: Using bash
        shell: bash -el {0}
        steps:
          - run: pip install pytest
          - run: pip install .
          - run: python -m xrst   --suppress_spell_warnings
          # bin/check_all.sh
