# 2024-04-26: see https://docs.github.com
#             /en/actions/learn-github-actions/understanding-github-actions
#
# The name for this workflow
name: example-workflow
#
# A short description of this workflow
run-name: This workflow was triggered by ${{ github.actor }}
#
# This worflow will be run on any push to the repository
on: [push]
#
# env.varible_one. env.variable_two
env:
   variable_one: 1
   variable_two: 2
#
jobs:
   #
   example_matrix:
      #
      strategy:
         matrix:
            os: [ windows-latest, ubuntu-latest ]
      #
      runs-on: ${{ matrix.os }}
      steps:
         - run: echo 'variable_one = ${{ env.variable_one }}'
         - run: echo 'variable_two = ${{ env.variable_two }}'
